# Generated by Django 6.0.2 on 2026-04-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_hi', models.CharField(max_length=200)),
                ('title_fr', models.CharField(max_length=200)),
                ('content_en', models.TextField()),
                ('content_hi', models.TextField()),
                ('content_fr', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
